# Generated by Django 3.0.5 on 2020-04-27 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('rating', models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг')),
                ('year', models.DateField(auto_now=True, verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_author', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(verbose_name='Оценка')),
                ('voted_on', models.DateTimeField(auto_now=True, verbose_name='Дата оценки')),
                ('text', models.TextField(verbose_name='Текст')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.Title', verbose_name='Произведение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_vote', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_comment', to='api.Rewiew')),
            ],
        ),
    ]
