# Generated by Django 3.0.5 on 2020-04-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200427_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewiew',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='voted_on',
            new_name='pub_date',
        ),
    ]
