# Generated by Django 3.0.5 on 2020-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
